### ISSUE TITLE
"I've pinged internal support about this to see what happened." - Welps

### ISSUE THREAD

**Issue by DayOfShah** [rainbow-me/fee-suggestions#29]
Thank you Welps! You are a real one. (thats a complimentary statement regarding your  honesty and authenticity)

I can confirm that internal support is aware of this matter and of my communications, as they have requested that I not discuss the matter outside of a private email thread. They then proceed to take no further action until/unless I communicate here. 

I thank you for your support. And if the workers of Rainbow are seeking to unionize, I fully support your efforts

 I've pinged internal support about this to see what happened.

_Originally posted by @welps in https://github.com/rainbow-me/fee-suggestions/issues/28#issuecomment-2106303953_

**Comment by DayOfShah** [comment]
Internal support could learn a thing or two from Welps

**Comment by welps** [comment]
please don't open a new issue for something like this. i don't appreciate this.

**Comment by DayOfShah** [comment]
Please dont defraud me ever again. I dont appreciate that
